name: fusion360
version: '0.3'
title: Autodesk Fusion 360 (Wine)
summary: Integrated CAD, CAM, CAE, and PCB software.
description: |
 Features
   *Parametric Modelling
   *Program tool paths for CNC machines
   *3D Rendering
   *Export STL models for the 3D Printer

icon: snap/gui/fusion360.png
base: core18
grade: stable
confinement: strict

architectures:
  - build-on: amd64

plugs:
  wine-runtime:
    interface: content
    target: $SNAP/wine-runtime
    default-provider: wine-platform-runtime
  wine-6-staging:
    interface: content
    target: $SNAP/wine-platform
    default-provider: wine-platform-6-staging

environment:
  WINEDLLOVERRIDES: "mscoree,mshtml="
  TRICKS: "corefonts msxml4 msxml6 vcrun2017 fontsmooth=rgb win10"
  WINEESYNC: 1
  SNAP_SUPPORT_URL: "https://github.com/Thermionix/fusion360/issues"

apps:
  fusion360:
    extensions: [gnome-3-28]
    command: bin/sommelier run-exe
    environment:
      RUN_EXE: "C:/Program Files/Autodesk/webdeploy/production/6a0c9611291d45bb9226980209917c3d/FusionLauncher.exe"
      INSTALL_URL: "https://dl.appstreaming.autodesk.com/production/installers/Fusion%20360%20Admin%20Install.exe"
      INSTALL_FLAGS: "-p deploy -g -f log.txt --quiet"
    plugs:
    - home
    - opengl
    - network
    - audio-playback
  wine:
    extensions: [gnome-3-28]
    command: bin/sommelier
    plugs:
      - home
      - network
  winetricks:
    extensions: [gnome-3-28]
    command: bin/sommelier winetricks
    plugs:
      - home
      - network

parts:
  hooks:
    plugin: dump
    source: hooks/
    organize:
      "*": sommelier/hooks/
    stage:
      - sommelier
    
  sommelier:
    plugin: make
    source: https://github.com/galgalesh/sommelier-core.git
    source-branch: "1.0"
